
- hosts: localhost
  gather_facts: no
  vars:
    outdir: out/
    passphrase: passphrase
  tasks:

  - name: create dir
    file:
      path: "{{ outdir }}/ca"
      state: directory

  - name: create private key
    openssl_privatekey:
      passphrase: "{{ passphrase }}"
      path: "{{ outdir }}/ca/ca.key"
      state: present
      cipher: auto
      type: ECC
      curve: secp384r1

  - name: check certificate exists
    local_action:
      module: stat
      path: "{{ outdir }}/ca/ca.crt"
    register: cert_stat

  - name: create CSR
    openssl_csr:
      privatekey_path: "{{ outdir }}/ca/ca.key"
      privatekey_passphrase: "{{ passphrase }}"
      path: "{{ outdir }}/ca/ca.csr"
      state: present
      common_name: moremagic
      basic_constraints_critical: yes
      basic_constraints:
        - CA:TRUE
    when: not cert_stat.stat.exists
      
  - name: create certificate
    openssl_certificate:
      privatekey_path: "{{ outdir }}/ca/ca.key"
      privatekey_passphrase: "{{ passphrase }}"
      csr_path: "{{ outdir }}/ca/ca.csr"
      path: "{{ outdir }}/ca/ca.crt"
      state: present
      provider: selfsigned
    when: not cert_stat.stat.exists

  - name: delete unneeded files
    local_action:
      module: file
      path: "{{ item }}"
      state: absent
    loop:
      - "{{ outdir }}/ca/ca.csr"

