
- hosts: all
  gather_facts: no
  vars:
    outdir: out/
    passphrase: passphrase
  tasks:
  - import_tasks: server_cert.yaml
  - import_tasks: nginx.yaml
    become: true
    become_method: sudo
  - import_tasks: data.yaml
    become: true
    become_method: sudo

