location /reader/ {
    include uwsgi_params;
    uwsgi_pass unix:/apps/reader/uwsgi/sock;
}
location = /reader { rewrite ^ /reader/; }
location /reader/static/ {
    alias /apps/reader/lib/python{{ python_version }}/site-packages/reader/_app/static/;
}

location /reader/legacy/ {
    include uwsgi_params;
    uwsgi_pass unix:/apps/reader/uwsgi/sock-legacy;
}
location = /reader/legacy { rewrite ^ /reader/legacy/; }
location /reader/legacy/static/ {
    alias /apps/reader/lib/python{{ python_version }}/site-packages/reader/_app/legacy/static/;
}
