
reader:
  url: /data/www-data/reader.sqlite
  feed_root: null
  reserved_name_scheme:
    reader_prefix: '.'
    plugin_prefix: '.'
    separator: '.'

  plugins:
    reader._plugins.tumblr_gdpr:tumblr_gdpr:
    reader._plugins.sqlite_releases:init:
    reader._plugins.twitter:init_reader:
    reader.ua_fallback:
    reader.mark_as_read:
    reader.entry_dedupe:
    reader.readtime:

cli:

  defaults:
    update:
      verbose: 3
    search:
      update:
        verbose: 1

app:
  reader:
    plugins:
      reader.enclosure_dedupe:

  plugins:
    reader._plugins.enclosure_tags:init:
    reader._plugins.preview_feed_list:init:

