
reader:
  url: /data/www-data/reader.sqlite
  feed_root: null

  plugins:
    reader._plugins.tumblr_gdpr:tumblr_gdpr:
    reader._plugins.ua_fallback:init:
    reader._plugins.sqlite_releases:init:

cli:
  reader:
    plugins:
      reader._plugins.regex_mark_as_read:regex_mark_as_read:
      reader._plugins.feed_entry_dedupe:feed_entry_dedupe:

  defaults:
    update:
      verbose: 3
    search:
      update:
        verbose: 1

app:
  reader:
    plugins:
      reader._plugins.enclosure_dedupe:enclosure_dedupe:

  plugins:
    reader._plugins.enclosure_tags:init:
    reader._plugins.preview_feed_list:init:

